frontend:
  type: ClusterIP
  port: 4000
  targetport: 8080
  containerport: 8080
  image: docker.artifactory.euw.platformservices.io/bpe/guestbook-frontend:1.0.2
redismaster:
  type: ClusterIP
  image: docker.artifactory.euw.platformservices.io/redis:5.0.14
  port: 6379
redisslave:
  type: ClusterIP
  image: docker.artifactory.euw.platformservices.io/redis:5.0.14
  port: 6379
