apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: {{ .Values.redisslave.image }}
        ports:
        - containerPort: {{ .Values.redisslave.port }}
        command: ["redis-server", "--slaveof", "redis-master", "{{ .Values.redisslave.port }}"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
spec:
  type: {{ .Values.redisslave.type }}
  selector:
    app: redis-slave
  ports:
  - name: redis
    protocol: TCP
    port: {{ .Values.redisslave.port }}
    targetPort: {{ .Values.redisslave.port }}
