apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-leader
  template:
    metadata:
      labels:
        app: redis-leader
    spec:
      containers:
      - name: redis-leader
        image: {{ .Values.redisleader.image }}
        ports:
        - containerPort: {{ .Values.redisleader.port }}
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir:
          sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-leader
  name: redis-leader
spec:
  type: {{ .Values.redisleader.type }}
  selector:
    app: redis-leader
  ports:
  - name: redis
    protocol: TCP
    port: {{ .Values.redisleader.port }}
    targetPort: {{ .Values.redisleader.port }}
