apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-follower
  template:
    metadata:
      labels:
        app: redis-follower
    spec:
      containers:
      - name: redis-follower
        image: {{ .Values.redisfollower.image }}
        ports:
        - containerPort: {{ .Values.redisfollower.port }}
        command: ["redis-server", "--replicaof", "redis-leader", "{{ .Values.redisfollower.port }}"]
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir:
          sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-follower
  name: redis-follower
spec:
  type: {{ .Values.redisfollower.type }}
  selector:
    app: redis-follower
  ports:
  - name: redis
    protocol: TCP
    port: {{ .Values.redisfollower.port }}
    targetPort: {{ .Values.redisfollower.port }}
